name: eoffice
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_svg: ^2.1.0
  google_fonts: ^6.2.1
  syncfusion_flutter_charts: ^30.1.39
  intl: ^0.20.2
  flutter_advanced_drawer: ^1.5.0
  flutter_secure_storage: ^9.2.4
  flutter_dotenv: ^5.2.1
  dio: ^5.8.0+1
  jwt_decoder: ^2.0.1
  currency_text_input_formatter: ^2.3.0
  lazy_load_scrollview: ^1.3.0
  qr_code_scanner_plus: ^2.0.10+1
  badges: ^3.1.2
  flutter_speed_dial: ^7.0.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  open_file: ^3.5.10
  share_plus: ^11.0.0
  flutter_slidable: ^4.0.0
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  package_info_plus: ^8.3.0
  http: ^1.5.0
  file_picker: ^10.3.1
  flutter_image_compress: ^2.4.0
  archive: ^4.0.7
  pdf: ^3.11.3
  flutter_localization: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/jpg/
    - assets/png/
    - .env
